import type {
  ContributorRole,
  DistributionProviderProfile,
} from "./provider.types";

export const allContributorRoles: ContributorRole[] = [
  "COMPOSER",
  "LYRICIST",
  "SONGWRITER",
  "ARRANGER",
  "TRANSLATOR",
  "ADAPTER",
  "LEAD_VOCALIST",
  "BACKGROUND_VOCALIST",
  "PERFORMER",
  "INSTRUMENTALIST",
  "CONDUCTOR",
  "ORCHESTRA",
  "CHOIR",
  "PRODUCER",
  "CO_PRODUCER",
  "EXECUTIVE_PRODUCER",
  "MIXING_ENGINEER",
  "MASTERING_ENGINEER",
  "RECORDING_ENGINEER",
];

export const defaultDistributionProviderProfiles: DistributionProviderProfile[] =
  [
    {
      id: "INTERNAL",
      name: "Radarune",
      enabled: true,
      priority: 10,
      deliveryMode: "INTERNAL",
      requirements: {
        releaseFields: {
          required: [
            "title",
            "primaryLanguage",
            "primaryGenre",
            "copyrightP",
            "copyrightC",
            "plannedReleaseDate",
          ],
          optional: [
            "versionTitle",
            "versionType",
            "metadataLanguage",
            "secondaryGenre",
            "labelId",
            "catalogNumber",
            "upc",
            "courtesyLine",
            "originalReleaseDate",
            "previouslyReleased",
          ],
        },
        trackFields: {
          required: [
            "title",
            "trackNumber",
            "discNumber",
            "language",
            "explicit",
            "instrumental",
          ],
          optional: [
            "versionTitle",
            "versionType",
            "metadataLanguage",
            "previouslyReleased",
            "isrc",
            "lyrics",
            "previewStartSeconds",
          ],
        },
        contributors: {
          requireLegalName: false,
          requireFirstAndLastName: false,
          requireSharePercentage: false,
          requireShareTotal100: false,
          requiredCategories: ["COMPOSITION", "PRODUCTION"],
          allowedRoles: allContributorRoles,
        },
        artwork: {
          required: true,
          minimumWidth: 3000,
          minimumHeight: 3000,
          square: true,
          allowedFormats: ["JPEG", "PNG"],
          maximumFileSizeMb: 20,
          requireRgb: true,
        },
        audio: {
          required: true,
          allowedFormats: ["WAV", "FLAC"],
          minimumSampleRateHz: 44100,
          minimumBitDepth: 16,
          allowMono: true,
          allowStereo: true,
          allowFloatingPointWav: false,
        },
        codes: {
          canAssignUpc: true,
          canAssignIsrc: true,
          requireExistingUpcWhenPreviouslyReleased: true,
          requireExistingIsrcWhenPreviouslyReleased: true,
        },
        rights: {
          requireMasterRightsDeclaration: true,
          requireCompositionRightsDeclaration: true,
          requireSampleDeclaration: true,
          requireCoverDeclaration: true,
          requireRemixDeclaration: true,
          requireAiContentDeclaration: true,
        },
      },
    },

    {
      id: "ONERPM",
      name: "ONErpm",
      enabled: false,
      priority: 20,
      deliveryMode: "MANUAL_EXPORT",
      requirements: {
        releaseFields: {
          required: [
            "title",
            "primaryLanguage",
            "primaryGenre",
            "copyrightP",
            "copyrightC",
            "plannedReleaseDate",
          ],
          optional: [
            "versionTitle",
            "versionType",
            "metadataLanguage",
            "secondaryGenre",
            "labelId",
            "catalogNumber",
            "upc",
            "courtesyLine",
            "originalReleaseDate",
            "previouslyReleased",
          ],
        },
        trackFields: {
          required: [
            "title",
            "trackNumber",
            "discNumber",
            "language",
            "explicit",
            "instrumental",
          ],
          optional: [
            "versionTitle",
            "versionType",
            "metadataLanguage",
            "previouslyReleased",
            "isrc",
            "lyrics",
            "previewStartSeconds",
          ],
        },
        contributors: {
          requireLegalName: true,
          requireFirstAndLastName: true,
          requireSharePercentage: false,
          requireShareTotal100: false,
          requiredCategories: ["COMPOSITION", "PRODUCTION"],
          allowedRoles: allContributorRoles,
        },
        artwork: {
          required: true,
          minimumWidth: 3000,
          minimumHeight: 3000,
          square: true,
          allowedFormats: ["JPEG", "PNG"],
          maximumFileSizeMb: 20,
          requireRgb: true,
        },
        audio: {
          required: true,
          allowedFormats: ["WAV", "FLAC"],
          minimumSampleRateHz: 44100,
          minimumBitDepth: 16,
          allowMono: true,
          allowStereo: true,
          allowFloatingPointWav: false,
        },
        codes: {
          canAssignUpc: true,
          canAssignIsrc: true,
          requireExistingUpcWhenPreviouslyReleased: true,
          requireExistingIsrcWhenPreviouslyReleased: true,
        },
        rights: {
          requireMasterRightsDeclaration: true,
          requireCompositionRightsDeclaration: true,
          requireSampleDeclaration: true,
          requireCoverDeclaration: true,
          requireRemixDeclaration: true,
          requireAiContentDeclaration: true,
        },
      },
    },

    {
      id: "FUGA",
      name: "FUGA",
      enabled: false,
      priority: 30,
      deliveryMode: "MANUAL_EXPORT",
      requirements: {
        releaseFields: {
          required: [
            "title",
            "primaryLanguage",
            "metadataLanguage",
            "primaryGenre",
            "catalogNumber",
            "copyrightP",
            "copyrightC",
            "plannedReleaseDate",
          ],
          optional: [
            "versionTitle",
            "versionType",
            "secondaryGenre",
            "labelId",
            "upc",
            "courtesyLine",
            "originalReleaseDate",
            "previouslyReleased",
          ],
        },
        trackFields: {
          required: [
            "title",
            "trackNumber",
            "discNumber",
            "language",
            "metadataLanguage",
            "explicit",
            "instrumental",
          ],
          optional: [
            "versionTitle",
            "versionType",
            "previouslyReleased",
            "isrc",
            "lyrics",
            "previewStartSeconds",
          ],
        },
        contributors: {
          requireLegalName: true,
          requireFirstAndLastName: true,
          requireSharePercentage: false,
          requireShareTotal100: false,
          requiredCategories: [
            "COMPOSITION",
            "PERFORMANCE",
            "PRODUCTION",
          ],
          allowedRoles: allContributorRoles,
        },
        artwork: {
          required: true,
          minimumWidth: 3000,
          minimumHeight: 3000,
          square: true,
          allowedFormats: ["JPEG", "PNG"],
          maximumFileSizeMb: 20,
          requireRgb: true,
        },
        audio: {
          required: true,
          allowedFormats: ["WAV", "FLAC"],
          minimumSampleRateHz: 44100,
          minimumBitDepth: 16,
          allowMono: true,
          allowStereo: true,
          allowFloatingPointWav: false,
        },
        codes: {
          canAssignUpc: false,
          canAssignIsrc: false,
          requireExistingUpcWhenPreviouslyReleased: true,
          requireExistingIsrcWhenPreviouslyReleased: true,
        },
        rights: {
          requireMasterRightsDeclaration: true,
          requireCompositionRightsDeclaration: true,
          requireSampleDeclaration: true,
          requireCoverDeclaration: true,
          requireRemixDeclaration: true,
          requireAiContentDeclaration: true,
        },
      },
    },
  ];
