// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Prisma CLI must follow the same precedence as Next.js in local development.
// Loading `.env` first and `.env.local` second prevents accidental commands
// against the hosted database when a developer explicitly selected localhost.
dotenv.config({ path: ".env" });
// `.env.local` is intentionally local-only. Loading it during a production
// migration can silently point Prisma at a developer machine or stale DB.
// The argv check also protects a manually executed `prisma migrate deploy`
// when the hosting panel forgot to set NODE_ENV.
const isProductionMigration =
  process.env.NODE_ENV === "production" || process.argv.includes("deploy");
if (!isProductionMigration) {
  dotenv.config({ path: ".env.local", override: true });
}

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is required to run Prisma.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
