-- Add URL-free search based import sources.
ALTER TABLE `ImportSource` MODIFY `type` ENUM('YOUTUBE_SEARCH', 'YOUTUBE_CHANNEL', 'YOUTUBE_PLAYLIST', 'SPOTIFY_ARTIST', 'SPOTIFY_PLAYLIST', 'SPOTIFY_ALBUM', 'SPOTIFY_SEARCH', 'MANUAL_URL') NOT NULL;
ALTER TABLE `ImportSource` ADD COLUMN `maxItems` INTEGER NOT NULL DEFAULT 100 AFTER `maxAgeDays`;
