module.exports = {
  apps: [
    {
      name: "radarune-web",
      cwd: "/var/www/radarune/current",
      script: "npm",
      args: "run start",
      env: { NODE_ENV: "production" },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "768M",
      time: true,
    },
    {
      name: "radarune-worker-distribution",
      cwd: "/var/www/radarune/current",
      script: "npm",
      args: "run worker:distribution",
      env: { NODE_ENV: "production" },
      autorestart: true,
      max_memory_restart: "512M",
      time: true,
    },
    {
      name: "radarune-worker-intelligence",
      cwd: "/var/www/radarune/current",
      script: "npm",
      args: "run worker:intelligence",
      env: { NODE_ENV: "production" },
      autorestart: true,
      max_memory_restart: "512M",
      time: true,
    },
    {
      name: "radarune-worker-notifications",
      cwd: "/var/www/radarune/current",
      script: "npm",
      args: "run worker:notifications",
      env: { NODE_ENV: "production" },
      autorestart: true,
      max_memory_restart: "384M",
      time: true,
    },
    {
      name: "radarune-worker-onerpm-catalog",
      cwd: "/var/www/radarune/current",
      script: "npm",
      args: "run worker:onerpm-catalog",
      env: { NODE_ENV: "production" },
      autorestart: true,
      max_memory_restart: "512M",
      time: true,
    },
  ],
};
