import "server-only";
import { z } from "zod";
import { encryptBillingSecret, decryptBillingSecret } from "@/features/billing/server/lib/crypto";
import { prisma } from "@/server/prisma/prisma";
import { assertAdminPermission } from "@/features/admin/server/admin-context";
import { auditLogService } from "@/features/finance/server/services/audit-log.service";
import type { FinanceActorContext } from "@/features/finance/server/services/finance-access.service";
const schema=z.object({provider:z.enum(["YOUTUBE","SPOTIFY"]),credentials:z.record(z.string(),z.string().trim().min(1))});
export class IntegrationCredentialService { async list(actor:FinanceActorContext){assertAdminPermission(actor,"integrations.spotify.view");const rows=await prisma.integrationCredential.findMany({where:{organizationId:actor.organizationId},select:{provider:true,active:true,lastTestedAt:true,lastTestError:true,credentialsEncrypted:true}});return rows.map(row=>({provider:row.provider,active:row.active,hasCredentials:Boolean(row.credentialsEncrypted),lastTestedAt:row.lastTestedAt,lastTestError:row.lastTestError}));} async upsert(actor:FinanceActorContext,input:unknown){assertAdminPermission(actor,"integrations.spotify.view");const parsed=schema.parse(input);const row=await prisma.integrationCredential.upsert({where:{organizationId_provider:{organizationId:actor.organizationId,provider:parsed.provider}},update:{credentialsEncrypted:encryptBillingSecret(JSON.stringify(parsed.credentials)),active:true,lastTestError:null},create:{organizationId:actor.organizationId,provider:parsed.provider,credentialsEncrypted:encryptBillingSecret(JSON.stringify(parsed.credentials))}});await auditLogService.create({organizationId:actor.organizationId,actorUserId:actor.userId,action:"INTEGRATION_CREDENTIAL_UPDATED",entityType:"IntegrationCredential",entityId:row.id,metadata:{provider:parsed.provider}});return {provider:row.provider,active:row.active,hasCredentials:true};} async runtime(organizationId:string,provider:"YOUTUBE"|"SPOTIFY"){const row=await prisma.integrationCredential.findUnique({where:{organizationId_provider:{organizationId,provider}}});return row?.active?JSON.parse(decryptBillingSecret(row.credentialsEncrypted)) as Record<string,string>:null;} }
export const integrationCredentialService=new IntegrationCredentialService();
