ALTER TABLE `AdminSetting`
  MODIFY COLUMN `key` ENUM(
    'PLATFORM_NAME', 'LOGO_URL', 'SUPPORT_EMAIL', 'SEO_TITLE', 'SEO_DESCRIPTION',
    'DEFAULT_DISTRIBUTION_PROVIDER', 'AUTO_DISTRIBUTION_ENABLED', 'MAX_AUDIO_FILE_SIZE_BYTES',
    'MAX_ARTWORK_FILE_SIZE_BYTES', 'MIN_ARTWORK_RESOLUTION', 'USER_REGISTRATION_ENABLED',
    'ARTIST_APPLICATIONS_ENABLED', 'EMAIL_VERIFICATION_REQUIRED', 'MAINTENANCE_MODE_ENABLED',
    'MAINTENANCE_MESSAGE', 'SEO_GOOGLE_SITE_VERIFICATION', 'SEO_INDEXING_ENABLED',
    'SMTP_MAIL_PROVIDER', 'SMTP_HOST', 'SMTP_PORT', 'SMTP_USERNAME', 'SMTP_PASSWORD',
    'SMTP_FROM_EMAIL', 'EMAIL_TEMPLATE_VERIFICATION_SUBJECT', 'EMAIL_TEMPLATE_VERIFICATION_BODY',
    'EMAIL_TEMPLATE_WELCOME_SUBJECT', 'EMAIL_TEMPLATE_WELCOME_BODY',
    'EMAIL_TEMPLATE_PASSWORD_RESET_SUBJECT', 'EMAIL_TEMPLATE_PASSWORD_RESET_BODY', 'SMTP_FROM_NAME',
    'EMAIL_BRAND_LOGO_URL', 'EMAIL_BRAND_PRIMARY_COLOR', 'EMAIL_BRAND_FOOTER_TEXT',
    'EMAIL_TEMPLATE_SIGN_IN_SUBJECT', 'EMAIL_TEMPLATE_SIGN_IN_BODY',
    'REWARD_EMAIL_VERIFICATION_REQUIRED', 'REWARD_MIN_ACTIVE_DAYS', 'REWARD_REAL_INTERACTION_REQUIRED'
  ) NOT NULL;
