import Link from "next/link";
import { Eye, Heart, MessageCircle, Music2, Play, Users } from "lucide-react";
import { artistChannelAnalyticsService } from "@/features/artist/server/services/artist-channel-analytics.service";

function Metric({ icon: Icon, label, value }: { icon: typeof Eye; label: string; value: number }) {
  return <div className="rounded-2xl border border-line bg-surface-strong p-4"><Icon className="size-4 text-accent" /><p className="mt-4 text-2xl font-semibold">{value.toLocaleString("tr-TR")}</p><p className="mt-1 text-xs text-muted">{label}</p></div>;
}

export async function ArtistChannelAnalytics({ actor, artistId }: { actor: { organizationId: string; userId: string; systemRole: string }; artistId?: string | undefined }) {
  const analytics = await artistChannelAnalyticsService.getForOwner(actor, artistId);
  return <section className="panel mt-6 overflow-hidden p-5 md:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">Kanal analizleri</p><h2 className="mt-2 text-2xl font-semibold">YouTube benzeri kanal özeti</h2><p className="mt-1 text-sm text-muted">Sadece yönetebildiğin sanatçı kanallarının verileri gösterilir.</p></div><Link className="rounded-xl border border-line px-3 py-2 text-xs font-semibold hover:border-accent" href="/artist-profile/analytics">Tüm kanallar</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Eye} label="Profil görüntülenmesi" value={analytics.summary.profileViews} /><Metric icon={Users} label="Tekil ziyaretçi" value={analytics.summary.uniqueViewers} /><Metric icon={Play} label="Geçerli stream" value={analytics.summary.streams} /><Metric icon={Heart} label="Beğeni" value={analytics.summary.likes} /></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><Metric icon={Users} label="Takipçi" value={analytics.summary.followers} /><Metric icon={MessageCircle} label="Yorum" value={analytics.summary.comments} /><Metric icon={Music2} label="Yayın" value={analytics.summary.releaseCount} /></div>{analytics.releases.length ? <div className="mt-6"><p className="text-sm font-semibold">En çok etkileşim alan yayınlar</p><div className="mt-3 space-y-2">{analytics.releases.map((release) => <div className="flex items-center justify-between rounded-xl border border-line bg-background px-3 py-3" key={`${release.artistId}-${release.id}`}><span className="truncate text-sm font-medium">{release.title}</span><span className="ml-3 shrink-0 text-xs text-muted">{release.likes.toLocaleString("tr-TR")} beğeni</span></div>)}</div></div> : null}</section>;
}
