import Link from "next/link";
import { PublicHeader } from "@/components/public-header";
import { PublicFooter } from "@/components/public-footer";
import { socialRepository } from "@/features/growth/server/repositories/social.repository";

export const dynamic = "force-dynamic";

const curated = [
  { slug: "en-cok-oylananlar", title: "En çok oylananlar", description: "Topluluğun oylarıyla öne çıkan yayınlar." },
  { slug: "en-fazla-dinlenenler", title: "En fazla dinlenenler", description: "En çok dinlenen ve tekrar keşfedilen şarkılar." },
  { slug: "global-dinlenenler", title: "Global dinlenenler", description: "Dünyadan Radarune dinleyicilerinin favorileri." },
];

export default async function ListsPage() {
  const playlists = await socialRepository.listPublicPlaylists();
  const curatedWithData = curated.map((item, index) => ({ ...item, index, playlist: playlists.find((entry) => entry.slug === item.slug) }));
  const communityPlaylists = playlists.filter((playlist) => !curated.some((item) => item.slug === playlist.slug));
  return <div className="min-h-screen bg-background text-foreground"><PublicHeader /><main className="page-shell space-y-6 pb-16">
    <section className="relative overflow-hidden rounded-[2rem] border border-line bg-[#0b1114] px-7 py-10 text-white shadow-2xl md:px-12 md:py-14">
      <div className="pointer-events-none absolute -right-28 -top-32 h-80 w-80 rounded-full bg-accent/35 blur-3xl" /><div className="pointer-events-none absolute -bottom-40 left-1/3 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl" />
      <div className="relative grid gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-accent">RADARUNE / PLAYLIST LAB</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold tracking-[-0.04em] md:text-7xl">Müziğin <span className="text-accent">küratörlüğü</span> sende.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/65 md:text-lg">Topluluğun oylarıyla yükselenleri, en çok dinlenenleri ve dünyanın her yerinden seçilen şarkıları tek bir akışta keşfet.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="rounded-full bg-accent px-5 py-3 text-sm font-semibold text-accent-foreground" href="/discover">Keşfe başla ↗</Link><Link className="rounded-full border border-white/20 px-5 py-3 text-sm font-semibold text-white hover:bg-white/10" href="/playlists">Kendi listeni oluştur</Link></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-3xl font-semibold text-accent">{playlists.length}</p><p className="mt-1 text-xs text-white/55">public liste</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-3xl font-semibold">{playlists.reduce((sum, item) => sum + item.tracks.length, 0)}</p><p className="mt-1 text-xs text-white/55">öne çıkan parça</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4 sm:col-span-2 lg:col-span-2"><p className="text-sm font-semibold">Gerçek topluluk verisi</p><p className="mt-1 text-xs leading-5 text-white/55">Listeler admin panelinden güncellenir; sahte sıralama veya uydurma içerik kullanılmaz.</p></div></div></div>
    </section>
    <section><div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-accent">Editoryal akış</p><h2 className="mt-2 text-2xl font-semibold md:text-3xl">Radarune seçkileri</h2></div><span className="text-xs text-muted">Admin tarafından yönetilir</span></div><div className="grid gap-4 lg:grid-cols-3">{curatedWithData.map((item) => <article className={`group relative min-h-80 overflow-hidden rounded-[1.75rem] border border-line p-6 ${item.index === 0 ? "bg-accent text-accent-foreground" : "bg-surface"}`} key={item.slug}><div className="flex items-start justify-between"><span className="text-xs font-semibold uppercase tracking-[0.2em] opacity-70">0{item.index + 1} / LİSTE</span><span className="text-2xl opacity-70">↗</span></div><h3 className="mt-12 max-w-[11rem] text-3xl font-semibold leading-tight">{item.title}</h3><p className="mt-3 max-w-xs text-sm leading-6 opacity-70">{item.description}</p><div className="absolute inset-x-6 bottom-6">{item.playlist ? <Link className={`inline-flex rounded-full px-4 py-2 text-sm font-semibold ${item.index === 0 ? "bg-black/15" : "bg-accent text-accent-foreground"}`} href={`/playlist/${item.playlist.slug ?? item.playlist.id}`}>Listeyi aç · {item.playlist.tracks.length} parça</Link> : <p className="rounded-xl border border-current/20 px-3 py-2 text-xs opacity-60">Bu seçki için henüz yayın eklenmedi.</p>}</div><div className="pointer-events-none absolute -bottom-16 -right-10 h-40 w-40 rounded-full border-[22px] border-current/10 transition-transform duration-500 group-hover:scale-125" /></article>)}</div></section>
    <section className="rounded-[1.75rem] border border-line bg-surface p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent">Topluluk koleksiyonu</p><h2 className="mt-2 text-2xl font-semibold">Diğer public listeler</h2></div><p className="text-sm text-muted">Kullanıcı ve ekip listeleri</p></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{communityPlaylists.map((playlist) => <Link className="group rounded-2xl border border-line bg-surface-strong p-4 transition hover:-translate-y-0.5 hover:border-accent" href={`/playlist/${playlist.slug ?? playlist.id}`} key={playlist.id}><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-accent/15 text-lg text-accent">♫</span><span className="text-lg text-muted transition group-hover:text-accent">↗</span></div><p className="mt-4 font-semibold">{playlist.name}</p><p className="mt-1 text-sm text-muted">{playlist.tracks.length} parça · {playlist.ownerUser.name}</p></Link>)}{communityPlaylists.length === 0 ? <div className="md:col-span-2 xl:col-span-3 rounded-2xl border border-dashed border-line p-8 text-center"><p className="font-semibold">Topluluk listeleri yakında burada.</p><p className="mt-1 text-sm text-muted">Admin panelinden public playlist yayınlandığında otomatik görünür.</p></div> : null}</div></section>
  </main><PublicFooter /></div>;
}
