"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { brandingUpdateSchema, type BrandingUpdateInput } from "@/features/platform/schemas/platform.schema";

export function BrandingEditor() {
  const [message, setMessage] = useState<string | null>(null);
  const router = useRouter();
  const { register, reset, setValue, handleSubmit, formState: { isSubmitting } } = useForm<BrandingUpdateInput>({ resolver: zodResolver(brandingUpdateSchema), defaultValues: { brandName: "", legalName: null, logoUrl: null, faviconUrl: null, supportEmail: null } });
  useEffect(() => { let active = true; void fetch("/api/admin/site-builder/branding").then(async (response) => { if (!response.ok) throw new Error("Marka ayarları yüklenemedi."); const value: unknown = await response.json(); if (active && value) reset(value as BrandingUpdateInput); }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : "Marka ayarları yüklenemedi."); }); return () => { active = false; }; }, [reset]);
  const save = async (input: BrandingUpdateInput) => { const response = await fetch("/api/admin/site-builder/branding", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); if (!response.ok) throw new Error("Marka ayarları kaydedilemedi."); setMessage("Marka ayarları kaydedildi. Site simgesini yenilemek için sayfa güncelleniyor…"); router.refresh(); };
  async function uploadMedia(file: File, kind: "LOGO" | "FAVICON") { const form = new FormData(); form.set("file", file); form.set("kind", kind); const response = await fetch("/api/admin/site-builder/branding/media", { method: "POST", body: form }); const result: unknown = await response.json(); if (!response.ok || typeof result !== "object" || result === null || !("url" in result) || typeof result.url !== "string") throw new Error(typeof result === "object" && result !== null && "error" in result && typeof result.error === "string" ? result.error : "Dosya yüklenemedi."); setValue(kind === "LOGO" ? "logoUrl" : "faviconUrl", result.url, { shouldDirty: true, shouldValidate: true }); setMessage(`${kind === "LOGO" ? "Logo" : "Favicon"} yüklendi. Kaydet düğmesine basarak etkinleştirin.`); }
  return <form className="panel grid gap-5 p-6" onSubmit={handleSubmit(save, () => setMessage("Marka alanlarını kontrol edin."))}>{message ? <p className="rounded-2xl border border-line bg-surface-strong p-3 text-sm">{message}</p> : null}<div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Marka adı<Input {...register("brandName")} /></label><label className="grid gap-2 text-sm font-medium">Yasal ad<Input {...register("legalName")} /></label><label className="grid gap-2 text-sm font-medium">Logo dosyası<input className="h-11 rounded-xl border border-line bg-transparent px-3 py-2 text-sm font-normal" accept="image/jpeg,image/png,image/webp" type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadMedia(file, "LOGO").catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Logo yüklenemedi.")); }} /><input type="hidden" {...register("logoUrl")} /><span className="text-xs font-normal text-muted">İdeal ölçü: 512x512 piksel. Şeffaf PNG önerilir; en az 256x256 olmalıdır.</span></label><label className="grid gap-2 text-sm font-medium">Favicon dosyası<input className="h-11 rounded-xl border border-line bg-transparent px-3 py-2 text-sm font-normal" accept="image/png,image/x-icon" type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadMedia(file, "FAVICON").catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Favicon yüklenemedi.")); }} /><input type="hidden" {...register("faviconUrl")} /><span className="text-xs font-normal text-muted">İdeal ölçü: 32x32 veya 48x48 piksel. PNG/ICO; 32–512 piksel aralığı.</span></label><label className="grid gap-2 text-sm font-medium">Destek e-postası<Input type="email" {...register("supportEmail")} /></label></div><Button disabled={isSubmitting} type="submit">Kaydet</Button></form>;
}
