"use client";

import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { discoverConfigUpdateSchema, type DiscoverConfigUpdateInput } from "@/features/platform/schemas/platform.schema";

const weightFields = [["validStream", "Geçerli stream"], ["uniqueListener", "Benzersiz dinleyici"], ["completionRate", "Tamamlama"], ["vote", "Oy"], ["like", "Beğeni"], ["share", "Paylaşım"]] as const;

export function DiscoverEditor() {
  const [message, setMessage] = useState<string | null>(null);
  const { register, reset, handleSubmit, formState: { isSubmitting } } = useForm<DiscoverConfigUpdateInput>({ resolver: zodResolver(discoverConfigUpdateSchema), defaultValues: { enabled: true, swipeEnabled: true, gridEnabled: true, listEnabled: true, defaultView: "GRID", cardTemplate: "PREMIUM", scoringWeights: { validStream: 1, uniqueListener: 1, completionRate: 1, vote: 1, like: 1, share: 1 } } });
  useEffect(() => { let active = true; void fetch("/api/admin/site-builder/discover").then(async (response) => { if (!response.ok) throw new Error("Discover ayarları yüklenemedi."); const value: unknown = await response.json(); if (active && value && typeof value === "object") reset(value as DiscoverConfigUpdateInput); }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : "Discover ayarları yüklenemedi."); }); return () => { active = false; }; }, [reset]);
  const save = async (input: DiscoverConfigUpdateInput) => { const response = await fetch("/api/admin/site-builder/discover", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...input, scoringWeights: Object.fromEntries(weightFields.map(([key]) => [key, Number(input.scoringWeights?.[key] ?? 0)])) }) }); if (!response.ok) throw new Error("Discover ayarları kaydedilemedi."); setMessage("Discover ayarları kaydedildi ve skor ağırlıkları normalize edildi."); };
  return <form className="panel grid gap-5 p-6" onSubmit={handleSubmit(save, () => setMessage("Discover ayarlarını kontrol edin."))}>{message ? <p className="rounded-2xl border border-line bg-surface-strong p-3 text-sm">{message}</p> : null}<div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" {...register("enabled")} /> Discover aktif</label><label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" {...register("votingEnabled")} /> Oylama aktif</label><label className="grid gap-2 text-sm font-medium">Sponsorlu içerik sıklığı<Input type="number" min="0" max="100" {...register("sponsorFrequency", { valueAsNumber: true })} /></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Varsayılan görünüm<select className="h-12 rounded-2xl border bg-white px-4" {...register("defaultView")}><option value="GRID">Grid</option><option value="SWIPE">Swipe</option><option value="LIST">Liste</option></select></label><label className="grid gap-2 text-sm font-medium">Kart şablonu<select className="h-12 rounded-2xl border bg-white px-4" {...register("cardTemplate")}><option value="MINIMAL">Minimal</option><option value="PREMIUM">Premium</option><option value="FULL_INFO">Tam bilgi</option><option value="SWIPE">Swipe</option><option value="VIDEO_STYLE">Video</option></select></label></div><div className="grid gap-4 sm:grid-cols-3">{weightFields.map(([key, label]) => <label className="grid gap-2 text-sm font-medium" key={key}>{label}<Input type="number" min="0" max="1" step="0.01" {...register(`scoringWeights.${key}`, { valueAsNumber: true })} /></label>)}</div><Button disabled={isSubmitting} type="submit">Ayarları kaydet</Button></form>;
}
