ALTER TABLE `ExternalMediaSource`
  MODIFY `provider` ENUM('YOUTUBE', 'SPOTIFY', 'ONE_RPM') NOT NULL;

ALTER TABLE `ImportSource`
  MODIFY `type` ENUM('YOUTUBE_SEARCH', 'YOUTUBE_CHANNEL', 'YOUTUBE_PLAYLIST', 'SPOTIFY_ARTIST', 'SPOTIFY_PLAYLIST', 'SPOTIFY_ALBUM', 'SPOTIFY_SEARCH', 'MANUAL_URL', 'ONERPM_CATALOG') NOT NULL,
  MODIFY `provider` ENUM('YOUTUBE', 'SPOTIFY', 'ONE_RPM') NULL;

ALTER TABLE `ImportItem`
  MODIFY `provider` ENUM('YOUTUBE', 'SPOTIFY', 'ONE_RPM') NOT NULL;
