import Link from "next/link";
import { ArrowUpRight, Flame, Sparkles, TrendingUp } from "lucide-react";
import { authSessionService } from "@/features/authentication/server/services/auth-session.service";
import { PublicGrowthShell } from "@/features/growth/components/public-shell";
import { discoverService } from "@/features/growth/server/services/discover.service";

export const dynamic = "force-dynamic";
export const metadata = { title: "Hype | Radarune", description: "Radarune topluluğunda ivme kazanan yeni şarkılar ve sanatçılar." };

export default async function HypePage() {
  const session = await authSessionService.getOptionalSession();
  const feed = (await discoverService.getFeed()).sort((a, b) => (b.likeCount ?? 0) - (a.likeCount ?? 0) || b.score - a.score).slice(0, 12);
  const artists = new Set(feed.map((item) => item.artist?.id).filter(Boolean)).size;
  return <PublicGrowthShell currentUser={session ? { name: session.user.name } : null}>
    <main className="relative overflow-hidden rounded-[2.4rem] bg-[#080f12] text-white shadow-[0_30px_100px_rgba(4,15,13,0.24)]">
      <div aria-hidden className="pointer-events-none absolute -left-24 -top-40 size-[480px] rounded-full bg-orange-400/20 blur-[110px]" /><div aria-hidden className="pointer-events-none absolute -right-20 top-20 size-[420px] rounded-full bg-emerald-400/15 blur-[110px]" />
      <section className="relative grid gap-10 px-6 py-12 sm:px-10 sm:py-16 lg:grid-cols-[1.15fr_.85fr] lg:items-end lg:px-14">
        <div><p className="inline-flex items-center gap-2 rounded-full border border-orange-300/25 bg-orange-300/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.22em] text-orange-200"><Flame className="size-3.5" />Radarune Hype</p><h1 className="mt-6 max-w-3xl text-5xl font-black tracking-[-0.06em] sm:text-7xl">Şimdi yükselenler.<span className="block text-orange-300">Sonra herkes dinler.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/55">Topluluk oyları, tazelik ve etkileşim ivmesiyle radarına giren yayınlar. Hype sıralaması gerçek Radarune verisinden beslenir.</p><div className="mt-8 flex flex-wrap gap-2"><Link className="rounded-full bg-orange-300 px-5 py-3 text-sm font-bold text-[#17100a]" href="/discover">Akışı aç →</Link><Link className="rounded-full border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-white/75" href="/lists">Listeleri incele</Link></div></div>
        <div className="rounded-[2rem] border border-white/10 bg-white/[0.06] p-5 backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-300">Pulse / şimdi</p><p className="mt-2 text-lg font-bold">Radarune sinyal özeti</p></div><Sparkles className="size-5 text-orange-300" /></div><div className="mt-6 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-black/20 p-3"><p className="text-2xl font-black text-orange-300">{feed.length}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-white/40">Yükselen</p></div><div className="rounded-2xl bg-black/20 p-3"><p className="text-2xl font-black text-emerald-300">{artists}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-white/40">Sanatçı</p></div><div className="rounded-2xl bg-black/20 p-3"><p className="text-2xl font-black">{feed.reduce((sum, item) => sum + (item.likeCount ?? 0), 0)}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-white/40">Oy</p></div></div><p className="mt-5 text-xs leading-5 text-white/45">AI öneri katmanı için hazır sinyaller: tazelik, oy ivmesi, kaynak ve sanatçı keşif bağlantısı.</p></div>
      </section>
      <section className="relative border-t border-white/10 bg-[#f5f8f6] px-4 py-8 text-[#101817] sm:px-8 sm:py-10"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-orange-700">Hype radar</p><h2 className="mt-2 text-3xl font-black tracking-[-0.05em]">İvme kazanan yayınlar</h2></div><span className="text-xs font-semibold text-[#74807b]">Gerçek zamanlı keşif</span></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{feed.map((item, index) => <article className="group rounded-[1.5rem] border border-black/[0.07] bg-white p-4 shadow-[0_14px_40px_rgba(15,23,42,0.05)] transition hover:-translate-y-1 hover:border-orange-300" key={item.id}><div className="flex items-center gap-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-2xl bg-orange-100 text-sm font-black text-orange-800">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><p className="truncate font-bold">{item.title}</p><p className="mt-1 truncate text-xs text-[#74807b]">{item.artist?.name ?? item.artistName} · {item.primaryGenre}</p></div><TrendingUp className="size-4 text-orange-600" /></div><div className="mt-4 flex items-center justify-between border-t border-black/[0.06] pt-3 text-xs text-[#74807b]"><span>{item.likeCount ?? 0} oy · sinyal {Math.round(item.score)}</span>{item.artist?.slug ? <Link className="inline-flex items-center gap-1 font-bold text-emerald-700" href={`/artist/${item.artist.slug}`}>Profil <ArrowUpRight className="size-3.5" /></Link> : <Link className="font-bold text-emerald-700" href="/discover">Keşfet →</Link>}</div></article>)}{feed.length === 0 ? <div className="rounded-2xl border border-dashed border-black/15 p-8 text-sm text-[#74807b] md:col-span-2 xl:col-span-3">Hype sinyali oluşması için henüz yeterli yayın verisi yok.</div> : null}</div></section>
    </main>
  </PublicGrowthShell>;
}
