export const billingFeatureKeys = [
  "artists.max",
  "team_members.max",
  "releases.draft.max",
  "releases.active.max",
  "storage.audio.max_bytes",
  "storage.artwork.max_bytes",
  "distribution.enabled",
  "distribution.providers.max",
  "distribution.priority",
  "analytics.advanced",
  "analytics.export",
  "royalties.enabled",
  "royalty_splits.max",
  "smart_links.enabled",
  "smart_links.max",
  "presave.enabled",
  "presave.max",
  "artist_profile.customization",
  "playlists.max",
  "social.stories.enabled",
  "analytics.smart_links",
  "analytics.presave",
  "ai.metadata.enabled",
  "ai.metadata.monthly_limit",
  "ai.artwork.enabled",
  "ai.audio.enabled",
  "ai.duplicate_detection.enabled",
  "ai.provider_rules.enabled",
  "ai.priority",
  "ai.history.max_days",
  "mobile.releases.enabled",
  "mobile.uploads.enabled",
  "mobile.discover.enabled",
  "mobile.player.enabled",
  "mobile.payouts.enabled",
  "mobile.presave.enabled",
  "mobile.intelligence.enabled",
  "mobile.social.enabled",
  "api.enabled",
  "api.rate_limit",
  "white_label.enabled",
  "custom_domain.enabled",
  "support.priority",
] as const;

export type BillingFeatureKey = (typeof billingFeatureKeys)[number];

export const billablePlanCodes = ["FREE", "ARTIST", "LABEL", "ENTERPRISE"] as const;
export type BillablePlanCode = (typeof billablePlanCodes)[number];
